### ISSUE TITLE
Long ranged melee weapons crash the game

### ISSUE THREAD

**Issue by Grash111** [Chaos-Awakens-Mod-Team/ChaosAwakens#132]
[crash-2024-08-04_03.21.07-client.txt](https://github.com/user-attachments/files/16486694/crash-2024-08-04_03.21.07-client.txt)
a way around it is to melee with a weapon that doesnt add range or just your bare fist and ect

**Comment by RaveTr** [comment]
Already fixed for next patch, was a pretty silly oversight by me lol. Keeping this open until then.

**Comment by uncertainluei** [comment]
It has been reported that it still happens on random occurrence, re-opening for the time being

**Comment by RaveTr** [comment]
Finally fixed in 0.12.1.0.

**Comment by uncertainluei** [comment]
Still occurs in 0.12.1.0 after the world gets re-loaded or the player respawns, as the `swingingArm` of `owner` in the `EntityUtil.applyReachModifierToEntity` method gets set to `null` upon meeting such criteria.
